# Generated by Django 4.1.8 on 2023-10-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_delete_intro_education_degree_work_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About'},
        ),
    ]
