# Generated by Django 4.1.8 on 2023-10-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_about_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdone',
            old_name='image',
            new_name='image_display',
        ),
        migrations.AddField(
            model_name='workdone',
            name='image_inside',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
