# Generated by Django 4.1.2 on 2023-10-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_rename_image_workdone_image_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
