# Generated by Django 4.1.2 on 2023-10-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_workdone_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdone',
            old_name='Project_url',
            new_name='project_url',
        ),
    ]
