# Generated by Django 4.1.2 on 2023-10-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_cv_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='workdone',
            name='image_display',
        ),
        migrations.RemoveField(
            model_name='workdone',
            name='image_inside',
        ),
        migrations.RemoveField(
            model_name='workdone',
            name='project_url',
        ),
    ]
